version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13

jobs:
  build_and_test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run Jest Tests
          command: npm test

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3-node-browsers
    steps:
      - checkout

      - aws-cli/install

      - aws-cli/configure
          profile-name: circleci

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      # build and deploy Storybook
      - run:
          name: Build StoryBook
          command: npm run build-storybook
      - run:
          name: Deploy Quiz Us Storybook
          command: aws s3 sync ./storybook-static s3://storybook-quizus
          # access at: http://storybook-quizus.s3-website-us-west-2.amazonaws.com

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          context: aws
          requires:
            - build_and_test
